/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class CdfTableProvider {

}

export declare class DeltaTableCreateBuilder {
  withColumns(jsonColumns: string): DeltaTableCreateBuilder
  withConfigurationProperty(prop: string, value?: string | undefined | null): DeltaTableCreateBuilder
  withTableName(name: string): DeltaTableCreateBuilder
  withPartitionColumns(columns: Array<string>): DeltaTableCreateBuilder
  withSaveMode(mode: string): DeltaTableCreateBuilder
  build(): Promise<RawDeltaTable>
}

export declare class RawCursor {
  /** Print the first 25 rows returned by the SQL query */
  show(): Promise<void>
  /**
   * Execute the given SQL command within the [SessionContext] of this instance
   *
   * **NOTE:** The function returns the rows as a continuous, newline delimited, stream of JSON strings
   * it is especially suited to deal with large results set.
   */
  stream(): ReadableStream<Buffer>
  /**
   * Execute the given SQL command within the [SessionContext] of this instance
   *
   * **NOTE:** Since this function returns a materialized JS Buffer,
   * it may result unexpected memory consumption for queries which return large data
   * sets.
   */
  fetchAll(): Promise<Buffer>
}

export declare class RawDeltaTable {
  /**
   * Create the Delta table from a path with an optional version.
   * Multiple StorageBackends are currently supported: AWS S3 and local URI.
   * Depending on the storage backend used, you could provide options values using the `options` parameter.
   *
   * This will not load the log, i.e. the table is not initialized. To get an initialized
   * table use the `load` function.
   *
   * # Arguments
   *
   * * `tableUri` - Path of the Delta table
   * * `options` - an object of the options to use for the storage backend
   */
  constructor(tableUri: string, options?: DeltaTableOptions | undefined | null)
  static create(tableUri: string, storageOptions?: AWSConfigKeyCredentials | AWSConfigKeyProfile | undefined | null): Promise<DeltaTableCreateBuilder>
  cdf(startVersion: number, endVersion: number): Promise<CdfTableProvider>
  static isDeltaTable(tableUri: string, storageOptions?: AWSConfigKeyCredentials | AWSConfigKeyProfile | undefined | null): Promise<boolean>
  /** Build the DeltaTable and load its state */
  load(): Promise<void>
  tableUri(): string
  version(): number
  hasFiles(): boolean
  files(): Promise<Array<string>>
  metadata(): DeltaTableMetadata
  protocol(): DeltaTableProtocolVersions
  /** Get the current schema of the Delta table. */
  schema(): string
  history(limit?: number | undefined | null): Promise<Array<CommitInfo>>
  /**
   * Run the Vacuum command on the Delta Table: list and delete files no longer
   * referenced by the Delta table and are older than the retention threshold.
   */
  vacuum(options?: DeltaTableVacuumOptions | undefined | null): Promise<Array<string>>
  /** Run the Optimize command on the Delta Table */
  optimize(kind: DeltaTableOptimizeType, options?: DeltaTableOptimizeOptions | undefined | null): Promise<DeltaTableOptimizeMetrics>
  write(data: Uint8Array | RawCursor, mode: string, options?: DeltaTableWriteOptions | undefined | null): Promise<void>
}

export declare class RawQueryBuilder {
  constructor()
  /**
   * Register the given [DeltaTable] into the [SessionContext] using the provided `table_name`
   *
   * Once called, the provided `delta_table` will be referenceable in SQL queries so long as
   * another table of the same name is not registered over it.
   */
  register(tableName: string, deltaTable: RawDeltaTable | CdfTableProvider): void
  /** Prepares the sql query to be executed. */
  sql(sqlQuery: string): RawCursor
}

export declare class Transaction {
  appId: string
  version: number
  lastUpdated?: number
  constructor(appId: string, version: number, lastUpdated?: number | undefined | null)
}
export type JsTransaction = Transaction

export interface AWSConfigKeyCredentials {
  awsRegion: string
  awsAccessKeyId: string
  awsSecretAccessKey: string
  awsSessionToken?: string
  awsEndpointUrl?: string
  awsConditionalPut?: string
}

export interface AWSConfigKeyProfile {
  awsRegion: string
  awsProfile: string
}

export interface BloomFilterProperties {
  setBloomFilterEnabled?: boolean
  fpp?: number
  ndv?: number
}

export interface ColumnProperties {
  dictionaryEnabled?: boolean
  statisticsEnabled?: string
  bloomFilterProperties?: BloomFilterProperties
}

export interface CommitInfo {
  timestamp?: number
  readVersion?: number
  isBlindAppend?: boolean
  engineInfo?: string
  info: Record<string, any>
  userMetadata?: string
}

export interface CommitProperties {
  customMetadata?: Record<string, string>
  maxCommitRetries?: number
  appTransactions?: Array<Transaction>
}

export interface DeltaTableMetadata {
  id: string
  name?: string
  description?: string
  partitionColumns: Array<string>
  createdTime?: number
  configuration: Record<string, string | undefined | null>
}

export interface DeltaTableOptimizeMetricDetails {
  /** Average file size of a operation */
  avg: number
  /** Maximum file size of a operation */
  max: number
  /** Minimum file size of a operation */
  min: number
  /** Number of files encountered during operation */
  totalFiles: number
  /** Sum of file sizes of a operation */
  totalSize: number
}

export interface DeltaTableOptimizeMetrics {
  /** Number of optimized files added */
  numFilesAdded: number
  /** Number of unoptimized files removed */
  numFilesRemoved: number
  /** Detailed metrics for the add operation */
  filesAdded: DeltaTableOptimizeMetricDetails
  /** Detailed metrics for the remove operation */
  filesRemoved: DeltaTableOptimizeMetricDetails
  /** Number of partitions that had at least one file optimized */
  partitionsOptimized: number
  /** The number of batches written */
  numBatches: number
  /** How many files were considered during optimization. Not every file considered is optimized */
  totalConsideredFiles: number
  /** How many files were considered for optimization but were skipped */
  totalFilesSkipped: number
  /** The order of records from source files is preserved */
  preserveInsertionOrder: boolean
}

export interface DeltaTableOptimizeOptions {
  zOrderFields?: Array<string>
  /** Properties of the transaction commit. If null, default values are used. */
  commitProperties?: CommitProperties
  /** filters for the optimize operation */
  filters?: Array<[string, string, string] | [string, string, Array<string>]>
}

export declare const enum DeltaTableOptimizeType {
  Compact = 'compact',
  ZOrder = 'z_order'
}

export interface DeltaTableOptions {
  /** Specify the version to load either as an integer or an ISO-8601/RFC-3339 timestamp. */
  version?: number | string
  /**
   * Indicates whether DeltaTable should track files.
   * This defaults to `true`
   *
   * Some append-only applications might have no need of tracking any files.
   * Hence, DeltaTable will be loaded with significant memory reduction.
   */
  withoutFiles?: boolean
  /** Set options used to initialize storage backend. */
  storageOptions?: AWSConfigKeyCredentials | AWSConfigKeyProfile
}

export interface DeltaTableProtocolVersions {
  minReaderVersion: number
  minWriterVersion: number
  readerFeatures?: Array<string>
  writerFeatures?: Array<string>
}

export interface DeltaTableVacuumOptions {
  /**
   * When true, list only the files, delete otherwise.
   * This defaults to `false`.
   */
  dryRun?: boolean
  /**
   * When falsed, accepts retention hours smaller than the value from
   * `delta.deletedFileRetentionDuration`.
   * This defaults to `true`.
   */
  enforceRetentionDuration?: boolean
  /**
   * the retention threshold in hours, if none then the value from
   * `delta.deletedFileRetentionDuration` is used or default of 1 week otherwise.
   */
  retentionHours?: number
  /** Properties of the transaction commit. If null, default values are used. */
  commitProperties?: CommitProperties
  /** Properties for the post commit hook. If null, default values are used. */
  postCommithookProperties?: PostCommitHookProperties
}

export interface DeltaTableWriteOptions {
  schemaMode?: string
  partitionBy?: Array<string>
  predicate?: string
  targetFileSize?: number
  name?: string
  description?: string
  configuration?: Record<string, string | undefined | null>
  writerProperties?: WriterProperties
  commitProperties?: CommitProperties
  postCommithookProperties?: PostCommitHookProperties
}

export interface PostCommitHookProperties {
  createCheckpoint?: boolean
  cleanupExpiredLogs?: boolean
}

export interface WriterProperties {
  dataPageSizeLimit?: number
  dictionaryPageSizeLimit?: number
  dataPageRowCountLimit?: number
  writeBatchSize?: number
  maxRowGroupSize?: number
  statisticsTruncateLength?: number
  compression?: string
  defaultColumnProperties?: ColumnProperties
  columnProperties?: Record<string, ColumnProperties | undefined | null>
}
